# Generated by Django 5.0.7 on 2024-07-31 01:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('input', models.TextField()),
                ('history', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
