# Generated by Django 5.0.7 on 2024-07-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('input', models.TextField()),
                ('history', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
